# This is a basic workflow that is manually triggered

name: Build Android Version

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildEnvAndSetUpApp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4
      - name: prepare environment
        run: |
         mkdir www
         rm -rf .github
         mv *.js *.css *.html -t www/
         mv assets/ bootstrap/ css/ data/ -t www/
         ls;
         docker run --rm -i -v $PWD:/workspace -w /workspace --privileged ghcr.io/alexjyong/cordovadocker:main sh -c "
         cordova platform add android;
         cordova build;
         "
                  
      - name: move file up
        run: |
         cp "$(find . -name '*.apk')" ~/

      - uses: actions/upload-artifact@v4
        with:
         name: my-apk-file
         path: ~/*.apk
         
      
        
        

