# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Use oxr463/setup-cordova
        uses: oxr463/setup-cordova@0.0.3
        with:
          exec: |
           mkdir www
           rm -rf .github
           mv *.js *.css *.html -t www/
           mv assets/ bootstrap/ css/ data/ res/ -t www/
           ls;
           cordova platform add android && \
           cordova build --no-telemetry && \
           cp "$(find . -name '*.apk')" ~/

      - uses: actions/upload-artifact@v3
        with:
         name: my-apk-file
         path: ~/*.apk
