# This is a basic workflow that is manually triggered

name: Deploy To Itch

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
   inputs:
      userName:
        description: 'Username for the itch repo'
        default: 'alexjyong'
        required: true
        type: string
      gameName:
        description: 'game name in the itch repo'
        default: 'seedship-relaunched-mirror'
        required: true
        type: string
      apiKey:
        description: 'api_key for repo'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DeployToItch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: move up
        run: |
          rm -rf .github #don't need this to be uploaded
          rm -rf .git
          rm -rf .git*
          cd ..; #move up from the game repo so we can compress it.
          zip -r SeedshipRelaunchWeb.zip SeedshipRelaunchWeb #compress the repo

          #download the butler application and make it an executable
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default \
          && unzip butler.zip \
          && chmod +x butler
          export BUTLER_API_KEY="${{ inputs.apiKey }}"
          ./butler push "SeedshipRelaunchWeb.zip" ${{ github.events.inputs.userName }}/${{ github.events.inputs.gameName }}:html5 

