# This is a basic workflow that is manually triggered

name: Deploy To Itch

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  DeployToItch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: move up
        run: |
          cd ..;
          zip -r SeedshipRelaunchWeb.zip SeedshipRelaunchWeb
          pwd;
          ls;
      - uses: manleydev/butler-publish-itchio-action@master
        env:
         BUTLER_CREDENTIALS: "OCDcFhETihdzp2Iv6YxydsFeiRfpc52YljMOHXxJ"
         CHANNEL: html5
         ITCH_GAME: seedship-relaunched-mirror
         ITCH_USER: alexjyong
         PACKAGE: /home/runner/work/SeedshipRelaunchWeb/SeedshipRelaunchWeb.zip
